{% set name = "napari-plugin-manager" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8912bd487b509ab9130308ecc14978d5dbce2d09b136662b27d0edf09536569c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - npe2
    - qtpy
    - superqt
    - pip
    # - napari >=0.4.18

test:
  imports:
    - napari_plugin_manager
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/napari/napari-plugin-manager
  summary: Install plugins for napari, in napari.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DragaDoncila
    - jni
    - czaki
    - jaimergp
    - goanpeca
